global:
  environment: prod
  deployId: latest
  imagePullSecrets: []

images:
  backend:
    repository: ghcr.io/laflut3/do-royal-backend
    tag: latest
  frontend:
    repository: ghcr.io/laflut3/do-royal-frontend
    tag: latest

backend:
  replicas: 1
  revisionHistoryLimit: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  secretName: do-royal

postgres:
  enabled: true
  image:
    repository: docker.io/library/postgres
    tag: "17-alpine"
  database: do_royal
  username: do_royal
  secretName: do-royal
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

externalSecret:
  enabled: false
  name: do-royal
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  vaultPath: prod/do-royal
  keys:
    serverPort: SERVER_PORT
    jdbcDatabaseUrl: JDBC_DATABASE_URL
    postgresDb: POSTGRES_DB
    postgresUser: POSTGRES_USER
    postgresPassword: POSTGRES_PASSWORD
    jwtSecret: DO_ROYAL_JWT_SECRET

frontend:
  replicas: 1
  revisionHistoryLimit: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

ingress:
  enabled: true
  name: do-royal
  className: traefik
  host: do-royal.polydo.dev
  tls:
    secretName: do-royal-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
