---
global:
  environment: prod
  deployId: 428c7e7a6f2c6e9d6be8e32210e7c775a86972fc
images:
  backend:
    repository: ghcr.io/laflut3/do-royal-backend
    tag: 1.4.0
  frontend:
    repository: ghcr.io/laflut3/do-royal-frontend
    tag: 1.4.0
ingress:
  host: do-royal.polydo.dev
  tls:
    secretName: do-royal-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
externalSecret:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  vaultPath: do-royal/prod
