---
global:
  environment: prod
  deployId: 2ab1c2c6801338b3262cd6cae2b2cb93955b8f77
images:
  backend:
    repository: ghcr.io/laflut3/do-royal-backend
    tag: 1.4.5
  frontend:
    repository: ghcr.io/laflut3/do-royal-frontend
    tag: 1.4.5
ingress:
  host: do-royal.polydo.dev
  tls:
    secretName: do-royal-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
backend:
  vault:
    secretPath: prod/do-royal
    k8sRole: do-royal-prod
