global:
  environment: prod
  deployId: latest

images:
  backend:
    repository: ghcr.io/laflut3/do-royal-backend
    tag: latest
  frontend:
    repository: ghcr.io/laflut3/do-royal-frontend
    tag: latest

ingress:
  host: do-royal.polydo.dev
  tls:
    secretName: do-royal-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
